### ISSUE TITLE
Change "npm start" to "node app.js"

### ISSUE THREAD

**Issue by ArneOb** [schul-cloud/wikimedia-content-adapter#4]
In general Node gets started as "node"
Please change the documentation accordingly.

**Comment by pinussilvestrus** [comment]
``npm start`` often wraps the ``node app.js`` command for quicker starting the node-app. That's because the start command can be bloated quickly when you have to use environment variables etc. So it's good style to write this command as ``npm start`` in the ``package.json``. Read more [here](https://coderwall.com/p/lwfndg/use-npm-start-to-launch-node-app). So I would stay at ``npm start`` 🙂

**Comment by ArneOb** [comment]
The title was misleading, sorry: please change the npm start from "nodejs app.js" to "node app.js" which is more common.
Sorry for my bad description.

**Comment by Charle42** [comment]
Is ready :+1:
